Bump github.com/zalando/skipper from 0.17.32 to 0.18.38 (#648)
* Bump github.com/zalando/skipper from 0.17.32 to 0.18.38

Bumps [github.com/zalando/skipper](https://github.com/zalando/skipper) from 0.17.32 to 0.18.38.
- [Release notes](https://github.com/zalando/skipper/releases)
- [Commits](https://github.com/zalando/skipper/compare/v0.17.32...v0.18.38)

---
updated-dependencies:
- dependency-name: github.com/zalando/skipper
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Get Dial directly from InClusterConfig instead of TransportConfig

client-go has dropped direct access to Dial from Transport, this commit
updates the usage to the upper layer, InClusterConfig.
- https://github.com/kubernetes/client-go/commit/5dab9a0b8438c16fe1572158c63b716e641ebeb4

Signed-off-by: Katyanna Moura <amelie.kn@gmail.com>

* Remove deprecated linters

deadcode and varcheck are deprecated. They're currenlty unused throughout the code, so no need for replacement.

Signed-off-by: Katyanna Moura <amelie.kn@gmail.com>

* Check error returned from client-go/SharedInformer.AddEventHandler

Fix lint error:
Error: kubernetes/pods.go:53:26: Error return value of
`informer.AddEventHandler` is not checked (errcheck)

Signed-off-by: Katyanna Moura <amelie.kn@gmail.com>

* fix update and pin k8s dependency to v0.24.17

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

* fix deps

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Katyanna Moura <amelie.kn@gmail.com>
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Katyanna Moura <amelie.kn@gmail.com>
Co-authored-by: Sandor Szücs <sandor.szuecs@zalando.de>